name: ASP.NET Core CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build with dotnet
      run: dotnet build src/Goblin.sln --configuration Release
    - name: Run tests
      run: dotnet test src/Goblin.sln 
